[project]
name = "pconv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AAAkater", email = "1318382761@qq.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
